<?php echo $this->doctype() . "\n"; ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php echo $this->headTitle() . "\n"; ?>

<!-- Javascript -->
<?php echo $this->headScript() . "\n"; ?>

<!-- Stylesheets -->
<?php echo $this->headLink() . "\n"; ?>

<!-- Shortcut icon -->
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />

<!-- Meta tags -->
<?php echo $this->headMeta() . "\n"; ?>
</head>
	<body>
		<h1>Jon is gay</h1>
		<?php echo $this->layout()->content; ?>
	</body>
</html>
